/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sony
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFilas = new javax.swing.JTextField();
        txtColumnas = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cmdCrear = new javax.swing.JButton();
        cmdManual = new javax.swing.JButton();
        cmdAutomatico = new javax.swing.JButton();
        cmdOperaciones = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablaResultado = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTablaInicial = new javax.swing.JTable();
        cmbOperaciones = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Vani", 3, 24)); // NOI18N
        jLabel1.setText("Operaciones De Matrices");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 320, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 11))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel2.setText("No. de Filas: ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel3.setText("No. de Columnas:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        jPanel2.add(txtFilas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 50, 30));
        jPanel2.add(txtColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 50, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 240, 110));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 11))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, -1));

        cmdManual.setText("Manual");
        cmdManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdManualActionPerformed(evt);
            }
        });
        jPanel3.add(cmdManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 100, -1));

        cmdAutomatico.setText("Automatico");
        cmdAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAutomaticoActionPerformed(evt);
            }
        });
        jPanel3.add(cmdAutomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 100, -1));

        cmdOperaciones.setText("Operaciones");
        cmdOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOperacionesActionPerformed(evt);
            }
        });
        jPanel3.add(cmdOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 100, -1));

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 100, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 630, 80));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 940, 10));

        tblTablaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblTablaResultado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 360, 290));

        tblTablaInicial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblTablaInicial);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 360, 290));

        cmbOperaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diagonal Secundaria", "Triangular Superior", "Letra A", "Letra T", "Letra E", "Letra F", "Letra P", "Letra I", "Letra N", " " }));
        jPanel1.add(cmbOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        int filas, columnas;
        DefaultTableModel t1, t2;

        filas = Integer.parseInt((txtFilas).getText());
        columnas = Integer.parseInt((txtColumnas).getText());

        t1 = (DefaultTableModel) tblTablaInicial.getModel();
        t2 = (DefaultTableModel) tblTablaResultado.getModel();

        t1.setRowCount(filas);
        t1.setColumnCount(columnas);

        t2.setRowCount(filas);
        t2.setColumnCount(columnas);
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdManualActionPerformed
        int filas, columnas, n, sw, res;
        boolean aux = true;

        columnas = tblTablaInicial.getColumnCount();
        filas = tblTablaResultado.getRowCount();

        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++) {
                do {
                    sw = 1;
                    try {

                        n = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el elemento en la Fila " + i + " y el la Columna " + j));
                        tblTablaInicial.setValueAt(n, i, j);

                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "Digite un Numero Valido", "Error", JOptionPane.ERROR_MESSAGE);
                        sw = 0;
                    } catch (NullPointerException e) {
                        res = JOptionPane.showConfirmDialog(this, "Seguro que decias salir", "Salir", JOptionPane.YES_OPTION);
                        if (res == 0) {
                            sw = 1;

                            i = filas;
                            j = columnas;

                            aux = false;
                        } else {
                            sw = 0;
                        }

                    }
                } while (sw == 0);

            }
        }


    }//GEN-LAST:event_cmdManualActionPerformed

    private void cmdAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAutomaticoActionPerformed
        int filas, columnas, n;

        columnas = tblTablaInicial.getColumnCount();
        filas = tblTablaResultado.getRowCount();

        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++) {
                n = (int) (Math.random() * 50 + 1);
                tblTablaInicial.setValueAt(n, i, j);
            }

        }

    }//GEN-LAST:event_cmdAutomaticoActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        int columnas, filas;
        DefaultTableModel t1, t2;

        columnas = tblTablaInicial.getColumnCount();
        filas = tblTablaResultado.getRowCount();

        txtFilas.setText("");
        txtColumnas.setText("");
        txtFilas.requestFocusInWindow();
        cmbOperaciones.setSelectedIndex(0);

        t1 = (DefaultTableModel) tblTablaInicial.getModel();
        t2 = (DefaultTableModel) tblTablaResultado.getModel();

        t1.setRowCount(0);
        t1.setColumnCount(0);

        t2.setRowCount(0);
        t2.setColumnCount(0);
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void cmdOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOperacionesActionPerformed
    int op, filas, columnas, aux, cont = 0;
    op = cmbOperaciones.getSelectedIndex();

    filas = tblTablaInicial.getRowCount();
    columnas = tblTablaInicial.getColumnCount();

    switch (op) {

        case 0:
            for (int i = 0; i < filas; i++) {
                for (int j = 0; j < columnas; j++) {
                    aux = (int) tblTablaInicial.getValueAt(i, j);

                    if (i == j) {
                    tblTablaResultado.setValueAt(aux, i, j);

                    }
                }
            }
        break;
        

        case 1:
            for (int i = 0; i < filas; i++) {
                for (int j = 0; j < columnas; j++) {
                    aux = (int) tblTablaInicial.getValueAt(i, j);
                   
                    if (i == j || i==0 || j==filas-1) {
                    tblTablaResultado.setValueAt(aux, i, j);

                    }     
                }
            }
        break;
  
        case 2:
            for (int i = 0; i < filas; i++) {
                for (int j = 0; j < columnas; j++) {
                    aux = (int) tblTablaInicial.getValueAt(i, j);
                   
                    if (i == 0 ||i==filas/2 || j==0 || j== columnas-1) {
                    tblTablaResultado.setValueAt(aux, i, j);

                    }     
                }
            }
        break;
        
        
        
        
        
        case 3:
            for (int i = 0; i < filas; i++) {
                for (int j = 0; j < columnas; j++) {
                    aux = (int) tblTablaInicial.getValueAt(i, j);
                   
                    if (i==0 || j==filas/2) {
                    tblTablaResultado.setValueAt(aux, i, j);

                    }     
                }
            }
        break;   
        
        case 4:
            for (int i = 0; i < filas; i++) {
                for (int j = 0; j < columnas; j++) {
                    aux = (int) tblTablaInicial.getValueAt(i, j);
                   
                    if (j==0 || i==0 || i==filas-1 || i==columnas/2){
                    tblTablaResultado.setValueAt(aux, i, j);

                    }     
                }
            }
        break; 
        
        case 5:
            for (int i = 0; i < filas; i++) {
                for (int j = 0; j < columnas; j++) {
                    aux = (int) tblTablaInicial.getValueAt(i, j);
                   
                    if (j==0 || i==0  || i==columnas/2){
                    tblTablaResultado.setValueAt(aux, i, j);

                    }     
                }
            }
        break; 
        
        case 6://Falta
            for (int i = 0; i < filas; i++) {
                for (int j = 0; j < columnas; j++) {
                    aux = (int) tblTablaInicial.getValueAt(i, j);
                   
                    if (j==0 || i==0  || i==columnas/2 || j==filas-1){
                    tblTablaResultado.setValueAt(aux, i, j);

                    }     
                }
            }
        break;
        
        case 7:
            for (int i = 0; i < filas; i++) {
                for (int j = 0; j < columnas; j++) {
                    aux = (int) tblTablaInicial.getValueAt(i, j);
                   
                    if (j==columnas/2 || i==filas-1 || i==0){
                    tblTablaResultado.setValueAt(aux, i, j);

                    }     
                }
            }
        break;
        
        case 8:
            for (int i = 0; i < filas; i++) {
                for (int j = 0; j < columnas; j++) {
                    aux = (int) tblTablaInicial.getValueAt(i, j);
                   
                    if (i==j || j==filas-1 || j==0){
                    tblTablaResultado.setValueAt(aux, i, j);

                    }     
                }
            }
        break;
        
        
        
        
        
        
  }
  
    }//GEN-LAST:event_cmdOperacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOperaciones;
    private javax.swing.JButton cmdAutomatico;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdManual;
    private javax.swing.JButton cmdOperaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblTablaInicial;
    private javax.swing.JTable tblTablaResultado;
    private javax.swing.JTextField txtColumnas;
    private javax.swing.JTextField txtFilas;
    // End of variables declaration//GEN-END:variables
}
